### ISSUE TITLE
Support for Tables Using GFM

### ISSUE THREAD

**Issue by Sealatron** [joeyespo/grip#102]
Does grip support tables when using the --gfm option? This is what I run:

    grip --gfm notes.md --export notes.html

But the table doesn't display at all in *notes.html*, all I see is

    | Table | Test | In | Grip |
    | ----- | ---- | -- | ---- |

I'm sure I'm just missing something obvious.

**Comment by joeyespo** [comment]
Does GitHub support it?

| Table | Test | In | Grip |
| ----- | ---- | -- | ---- |

It doesn't seem like it does. Sorry, that means this is out-of-scope until GitHub adds it first.

**Comment by Sealatron** [comment]
Oh wow now I'm really confused. New to markdown in general, but when I preview that code here I can see the Table correctly formatted. And I read about it here: https://help.github.com/articles/github-flavored-markdown/

|Table|Test|In|Github|
|-----|-----|---|----|

This is what I see in preview http://i.imgur.com/RuFThiX.png.

**Comment by joeyespo** [comment]
Interesting. When I copy/paste your example, it doesn't render a table.

| Table | Test | In | Grip |
| ----- | ---- | -- | ---- |

But when I copy/paste the table from your commend, it does.

|Table|Test|In|Github|
|-----|-----|---|----|

Now I feel like I'm missing something.

Try copy/pasting this one into a new markdown file and see if `grip --gfm new.md` works for you.

**Comment by joeyespo** [comment]
Ok. Looks like if I add a 3rd `-` to the 'In' column, it works:

| Table | Test | In | Github |
| ----- | ----- | --- | ---- |

**Comment by Sealatron** [comment]
Yeah, that was the problem. Works perfectly now! Thanks.

**Comment by joeyespo** [comment]
Awesome! Glad it all worked out :-)
