### ISSUE TITLE
Specify header in command line

### ISSUE THREAD

**Issue by getaaron** [joeyespo/grip#110]
The full path of the markdown file is used both in the `<title>` tags and in an `h3`:

```html
<div id="readme" class="boxed-group flush clearfix announce instapaper_body md">
              
    <h3>
        <span class="octicon octicon-book"></span>
        /Users/aaron/seven-layer-dip-recipe.md
    </h3>
```

Is it possible to add a command line argument that would replace this with an arbitrary string?

**Comment by jlhonora** [comment]
:+1:

**Comment by joeyespo** [comment]
This is a bug. It should show the filename relative to the path you entered. Not sure when I'll get to this. Want to take a look?

Thanks for the issue, @getaaron!

**Comment by joeyespo** [comment]
Ah, wait. Are you doing something similar to [your other issue](https://github.com/joeyespo/grip/issues/111)?

If you use `cd /Users/aaron/seven && grip --export \ layer\ dip.md` instead of `grip --export /Users/aaron/seven\ layer\ dip.md`, that should show the right title for you.

This behavior is actually as designed. This way, you know what file you're looking at when clicking around linked README files.

**Comment by jlhonora** [comment]
I think the title behave as expected. What I think he means (and is a feature I would appreciate as well) is this: to have a command line argument to customize the html's title and `h1` header content. Something like this:

```
grip input.md --export input.html --header='Some custom header'
```

that yields:

```
<title>Some custom header</title>
...
<div id="readme" class="boxed-group flush clearfix announce instapaper_body md">

<h3>
    <span class="octicon octicon-book"></span>
    Some custom header
</h3>
```

If you think it fits into your project's goals I can prepare a PR and discuss it.

**Comment by joeyespo** [comment]
@jlhonora Gotcha. Yeah, I mis-read this one. Yes, this would fit in for those using Grip as a scripting tool. I'd accept a PR that implemented this.

If you do get to it, could you call it `--title`? The CLI description can be something like "Manually sets the page's title. The default is the filename."

**Comment by joeyespo** [comment]
Fixed with #125.

**Comment by getaaron** [comment]
:+1: Thanks, @jlhonora!

**Comment by joeyespo** [comment]
Finally got around to wrapping everything up and deploying `v3.3.0` tonight. Thanks for your patience! Be sure to upgrade with `pip install --upgrade grip`.
