### ISSUE TITLE
Tell the gh api to enable anchors for --gfm

### ISSUE THREAD

**Issue by clawoflight** [joeyespo/grip#115]
When using this awesome [extension](https://packagecontrol.io/packages/MarkdownTOC) for sublime text, the anchor URL's don't work. However, they do when I use the sublime extension [markdown preview](https://packagecontrol.io/packages/Markdown%20Preview), they do.

Could you add a flag or default to the --gfm option that enables the anchors on github's side?

**Comment by joeyespo** [comment]
([Discussion on Twitter](https://twitter.com/ClawOfLight/status/590933363390812160).)
