### ISSUE TITLE
Perhaps it would be nice to have WYSIWYG possibility

### ISSUE THREAD

**Issue by kootenpv** [joeyespo/grip#121]
I'd like to see if it would be nice to edit in the localhost and then have it push back to the readme file once done. 

Not sure if it is possible and not sure if it would be an improvement, but just thought to throw it out there.

**Comment by joeyespo** [comment]
Yeah, this one does fall out of scope for this project, since it would require tightly integrating the rendering engine with an editor.

Thanks for the thought though!
