### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by netheril96** [joeyespo/grip#128]
When using grip lately, a warning is repeatedly output to the terminal

> /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

Apparently `grip` downloads resources without verifying the certificate of website. Hope this gets fixed soon.

**Comment by joeyespo** [comment]
It did (d43e5422bfd8ef6ec9ecd1041c1b74a2d109fc4d).

Thanks for the issue :-) 

New release will be up soon.

**Comment by joeyespo** [comment]
Just deployed `v3.3.0` which includes this fix. Be sure to `pip install --upgrade grip`!
