### ISSUE TITLE
Unable to set Page Title for exported HTML file

### ISSUE THREAD

**Issue by alanmb** [joeyespo/grip#130]
When exporting a file to HTML using grip 3.2.0, I used the method signature as described in the documentation:

```python
export(path=None, gfm=False, context=None, username=None, password=None, render_offline=False, render_wide=False, render_inline=True, out_filename=None, api_url=None, title=None)
```

But I got the following errors:

```
TypeError: export() got an unexpected keyword argument 'api_url'
TypeError: export() got an unexpected keyword argument 'title'
```

I tried using unnamed parameters, but then I would receive the message:

```
TypeError: export() takes at most 9 arguments (11 given)
```

It seems the *api_url* and *title* parameters are not found.

**Comment by joeyespo** [comment]
Ah yeah, this is part of the dev docs. If you clone `master` and `pip install .`, you'll be able to use these until the new release is ready.
