### ISSUE TITLE
Always load relative links, even if path in address bar doesn't end in "/"

### ISSUE THREAD

**Issue by bradparks** [joeyespo/grip#131]
I was testing a page, where markdown references in the file were relative to the files current location:

e.g. in my address bar I had typed

`http://localhost:5000/docs`

This worked, and rendered the README.md in that folder, but the relative links in the page were bad.

This isn't an issue in Github itself, and relative links load correctly in this situation.

**Comment by joeyespo** [comment]
Good call on this. GitHub used to have this same problem and it messed up relative links. Definitely worth fixing this.

I'll get to it after the next release (if nobody else jumps on it first).

**Comment by joeyespo** [comment]
Fixed in 8cfe46e8ade1195659bedbd964f12bbe980123b5.

**Comment by joeyespo** [comment]
Just deployed `v3.3.0` which contains the fix to this. Be sure to `pip install --upgrade grip` and feel free to reopen if you're still having an issue.

**Comment by bradparks** [comment]
hey! thanks for the fix.... fyi, when I tried this, i couldn't run `grip` anymore, and got an error:

    $ grip                                                                                                                                                                                                 14:46:21
    Traceback (most recent call last):
      File "/usr/local/bin/grip", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
        working_set.require(__requires__)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/py

the way I fixed it was found here:

http://stackoverflow.com/questions/7110360/easy-install-and-pip-doesnt-work

and simply required me to run:

`sudo easy_install Distribute`

after that was run, I could run grip again. I'm on a Mac. Thanks!

**Comment by joeyespo** [comment]
Interesting. I seem to run into things like that here and there. Sometimes running `pip uninstall grip` first seems to do the trick. Thanks for posting your fix!
