### ISSUE TITLE
table or list is not rendered correctly in render_offline mode

### ISSUE THREAD

**Issue by akawhy** [joeyespo/grip#132]
In **render_offline** mode, **table** or **list**(in some situation) is not rendered correctly. here is an example:

```

## list

1. AAAAAAAA

  * aa
  * bb

2. BBBBBBBB

  * aa
  * bb

## table

c1 | c2 | c3
-- | -- | --
| aa | bb
aa | | bb
aa | bb |
aa | bb | cc

```

Adding `tables`, `sane_lists` plugins can solve this problem.

**Comment by joeyespo** [comment]
FYI, just deployed `v3.3.0` which contains this fix.
