### ISSUE TITLE
RFC: Rename --gfm to --comments

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/grip#139]
There's been a few issues caused by the confusion of what `--gfm` does:
- #63
- #115 ([on Twitter](https://twitter.com/ClawOfLight/status/590933363390812160))
- https://github.com/joeyespo/grip/issues/137#issuecomment-135642614

I also see `--gfm` being used in a lot of `--export` examples. I wonder if that's the intention, or if people saw "--gfm" and thought "oh, GitHub Flavored Markdown, that's what I want":
- https://github.com/joeyespo/grip/issues/89#issue-51498170
- https://github.com/joeyespo/grip/issues/100#issue-59871549
- https://github.com/joeyespo/grip/issues/102
- https://github.com/joeyespo/grip/issues/129#issuecomment-110168717

As a reminder, `--gfm` comes directly from [the GitHub API](https://developer.github.com/v3/markdown/#parameters), but that doesn't mean we can't use a more meaningful name in Grip.

I'm thinking of renaming it to `--comments`, since that removes any ambiguity of what it's rendering. `--issues` is another suggestion (or as an alias), but in a way, all issues are comments, so I think using the more general name will be clear enough. It'll certainly be more clear than `--gfm`.

Thoughts from anyone here?

**Comment by joeyespo** [comment]
Renamed to `--user-content` in #150. The name comes from the [GitHub API docs](https://developer.github.com/v3/markdown/#parameters).

**Comment by clawoflight** [comment]
Yeah, that will clear up a lot of confusion :)
