### ISSUE TITLE
Rendering offline does not work

### ISSUE THREAD

**Issue by brian-bk** [joeyespo/grip#140]
Hello, I really like the project and I use it to render my notes to markdown. But sometimes I work offline, and grip does not work. I see there is a `render_offline` that is set as default to False, but nowhere else is it set.

By hardcoding in `render_offline = True` in renderers.py, I see it works, and it uses the cached github renderer.

Can you add either a ping test to the script to set `render_offline` or at the least an argument into the parser like `--render-offline`? Thanks.

**Comment by joeyespo** [comment]
There's currently a half-working implementation that isn't exposed to the CLI. #35 is the long-standing issue on this.

It'll eventually be production-ready, but is lower on the list at the moment. (I wouldn't be opposed to a PR that [exposed the CLI argument](https://github.com/joeyespo/grip/blob/70716253dbef37f0e51a4b5f6f1413e63d59aa05/grip/command.py#L106), but didn't document it in [the usage](https://github.com/joeyespo/grip/blob/70716253dbef37f0e51a4b5f6f1413e63d59aa05/grip/command.py#L8-L34) though.)

Thanks, @brian-bk.
