### ISSUE TITLE
Doesn't seem to handle GFM checkboxes

### ISSUE THREAD

**Issue by jwarner112** [joeyespo/grip#141]
Per [this](https://help.github.com/articles/github-flavored-markdown/) announcement, GFM should have support for checkboxes. It seems that `grip` happens not to handle this, yet.

Raw:
![image](https://cloud.githubusercontent.com/assets/2992409/10026797/c063d4a6-6131-11e5-86e1-3b474bf44569.png)

Rendered:
![image](https://cloud.githubusercontent.com/assets/2992409/10026771/99eba68c-6131-11e5-84ba-02373785060b.png)

**Comment by joeyespo** [comment]
This is unfortunately a [known issue](https://github.com/joeyespo/grip#known-issues).

Feel free to bump the [GitHub issue here](https://github.com/isaacs/github/issues/309) with a +1.

Thanks for the issue and for using Grip, @jwarner112!

**Comment by joeyespo** [comment]
Btw, I just [added](4be54fa28f7e14daaff27b5866f42bce852b4fc6) the word "checkboxes" to the Known Issues so it's more easily found.
