### ISSUE TITLE
Is it possible to do hot-reload?

### ISSUE THREAD

**Issue by octref** [joeyespo/grip#142]
Hey, I've been using grip for a long time and I love it.

Recently I'm doing some React development, and [`react-hot-loader`](http://gaearon.github.io/react-hot-loader/) has been immensely helpful.

Is it possible to do something similar in grip? Watching changes in `README.md` and live update the webpage.

**Comment by w0ng** [comment]
Yeah, it was merged in #135 and enabled by default. Can confirm it's working.

You need to install grip from Git, since the merge (Sept 22) happened after the current pip release (Jun 29).

**Comment by octref** [comment]
@w0ng 
Thanks!

**Comment by joeyespo** [comment]
@octref @w0ng FYI, this was published in 4.0.0. Run `pip uninstall grip` (if you installed from source), then `pip install --upgrade grip`. Thanks for the issue!
