### ISSUE TITLE
Task lists (checkbox) feature rendered in GFMs by Github API

### ISSUE THREAD

**Issue by tejasshah93** [joeyespo/grip#143]
I know this is a [known issue](https://github.com/joeyespo/grip#known-issues) as mentioned in README.md and I'm aware that this issue is referenced [here](https://github.com/isaacs/github/issues/309)

However, the API seems to be working with the expected behavior (contacted support@github.com). Here's what I'm seeing:

`$ curl https://api.github.com/markdown -X POST -d '{"mode":"gfm", "text":"- [ ] foo\n- [x] bar"}'`

    <ul class="task-list">
    <li class="task-list-item">
    <input type="checkbox" class="task-list-item-checkbox" disabled> foo</li>
    <li class="task-list-item">
    <input type="checkbox" class="task-list-item-checkbox" checked disabled> bar</li>
    </ul>

Notice that the task list input was converted to checkboxes in the output HTML.
So, where are we still stuck at?

**Comment by joeyespo** [comment]
Maybe they fixed it?

Could you try it without `"mode":"gfm"`? "GFM" is reserved for issues and comments. The problem from before is that checkboxes aren't rendered in "Readme" mode.

**Comment by joeyespo** [comment]
Here's what I saw.

Rendering with gfm works, like you've pointed out:

```py
>>> print(requests.post('https://api.github.com/markdown', data=json.dumps({'mode': 'gfm', 'text': '- [ ] foo\n- [x] bar'})).text)
<ul class="task-list">
<li class="task-list-item">
<input type="checkbox" class="task-list-item-checkbox" disabled> foo</li>
<li class="task-list-item">
<input type="checkbox" class="task-list-item-checkbox" checked disabled> bar</li>
</ul>
```

Rendering Readmes (i.e. not `gfm`) is what's broken:

```py
>>> print(requests.post('https://api.github.com/markdown', data=json.dumps({'text': '- [ ] foo\n- [x] bar'})).text)
<ul>
<li>[ ] foo</li>
<li>[x] bar</li>
</ul>
```

This is the Markdown API bug.

**Comment by joeyespo** [comment]
Thanks for the update and for pinging Github about this, @tejasshah93.

Closing for now. We can continue the conversation in https://github.com/isaacs/github/issues/309.

**Comment by tejasshah93** [comment]
@joeyespo yes indeed. Didn't look up earlier that "gfm" mode is only meant for user-content.
So basically, it works for the "gfm" mode but it's still broken for the default mode ("markdown") used for READMEs as you mentioned.

I've pinged the support regarding this too. Let's see what unfolds accordingly.
Thanks for the clarification.
