### ISSUE TITLE
Launch the url in the default browser on startup?

### ISSUE THREAD

**Issue by matanster** [joeyespo/grip#145]
This is an awesome library, saves you the trouble of giving shady chrome extensions access to read all your pages. Does it have an option to just launch a browser window with its port, when you start it on the command prompt? I've seen other developer-ish tools that do that, and haven't personally experienced a downside with that. This could make things smoother, if not already implemented.

**Comment by joeyespo** [comment]
It does as of v3.3.0. Run `grip -b` :smiley: 

Seems I forgot to document this in the Readme, so thanks for opening this issue!

**Comment by matanster** [comment]
:+1:
