### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by pronobis** [joeyespo/grip#152]
Running  `cat README.md | ~/.local/bin/grip - --export -` results in:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

The same file works just fine if I run regular server, i.e. `~/.local/bin/grip README.md`
System: Ubuntu 15.10

**Comment by joeyespo** [comment]
Ah, good catch! Fixed in e2a0a6a0fc85163c6e8de43f1313840e59cd59ac. If you need a workaround until this gets released, install from git with `pip install -e .`.

Thanks for the bug report, @pronobis!

**Comment by pronobis** [comment]
Thanks! Works great!

**Comment by cjchallis** [comment]
I am getting this error whether I serve or export.  I was doing both just fine until today and can't think of any changes made.  I'm using a 64-bit Ubuntu 15.04 VM running in VMware.  Any ideas?  I've never had any issues with grip before so I'm surprised it stopped working today.

**Comment by joeyespo** [comment]
@cjchallis That is strange. Even though nothing else changed, did you upgrade Grip recently?

What do you get when running `grip -V`?

**Comment by cjchallis** [comment]
Thanks for getting back to me.  No, I haven't updated Grip recently.  `grip -V` gives me `Grip 4.1.0`

**Comment by joeyespo** [comment]
Interesting. Not sure what would suddenly cause it to stop working. GitHub changed some things recently (namely, styles and asset URLs), but those changes shouldn't cause a 500.

In any case, 4.2 fixes Grip to work with those changes. Could you try upgrading to see if that helps?

```bash
$ pip install --upgrade grip
```
