### ISSUE TITLE
Prompt password in login 

### ISSUE THREAD

**Issue by mekoda** [joeyespo/grip#153]
Hi,

This is a minor improvement, but I think it can add a lot of value. This way, the password input in the login process would be *a la SSH* (silent input without showing characters). It's also more secure: will prevent issues related with *shoulder surfing*.

Instead of:

`$ grip --user <your-username> --pass <your-password>`

The process will be:

`$ grip --user <your-username>`
  
*\<cool message prompting the user password\>*

*\<authenticate if valid\>*

If it's okay, I can work on this.

**Comment by joeyespo** [comment]
Yes! :+1: 

Just to clarify, are you thinking it should prompt for a password when `--user` is present but not `--pass`? I like it. (Note that currently you can provide `--pass` without `--user` to use an auth token. A dedicated `--token` option may be added later, but let's keep this behavior for now.)

Go for it :smiley:

**Comment by mekoda** [comment]
Yes, exactly. 

The PR is done; changes in the 8413889cd326e853f3e69a5b27caabac581737ed commit.

**Comment by joeyespo** [comment]
Fantastic! Taking a look now.

**Comment by joeyespo** [comment]
Added with #154.

**Comment by joeyespo** [comment]
FYI, just published `v4.1.0` which contains this feature. Thanks again, @mekoda!

**Comment by mekoda** [comment]
Cool!

I will help enhancing the auth experience when having some free time. Thanks!
