### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by btcrooks** [joeyespo/grip#156]
Having the ability for grip to watch for changes of you .md files would be really neat! :+1:

**Comment by clawoflight** [comment]
This is already implemented.

**Comment by joeyespo** [comment]
Yep, @clawoflight is right. This is working as of 4.0.0 (PR #135).

Simply edit your Readme and the change will be reflected in the browser.

Feel free to re-open if something isn't working properly.

**Comment by btcrooks** [comment]
Ah! Did not see this! Apologies. Thanks guys! Cheers.

**Comment by joeyespo** [comment]
@btcrooks :smiley:
