### ISSUE TITLE
Using SVGs

### ISSUE THREAD

**Issue by akaleeroy** [joeyespo/grip#157]
Would it be possible to support SVG rendering?

    ![SVG doesn't work](image.svg)
or `<svg><path...`

Also it would be nice if there was an option to leave other file types alone and just let the browser render them as it would, without trying to parse them.

Thanks!

**Comment by joeyespo** [comment]
This works fine for me. What's the exact command you're running?

Here's what I tried:

#### Command

```bash
$ grip
```

#### Files

- **README.md**

   ```markdown
   Testing!
   ========
   
   ![SVG doesn't work](image.svg)
   ```

- **image.svg**

**Comment by akaleeroy** [comment]
I used `grip.exe --browser "$file"` and simply `grip`, and tried it in latest Firefox, Chrome and Opera. None of them worked. 

The latter 2 browsers show a broken image placeholder with a link. When I follow the link it's an empty Grip page. Firefox shows the alt-text as a plain link, and still nothing at `http://localhost:6419/image.svg`.

**Comment by joeyespo** [comment]
What is `$file`? Can you give me an example of what that resolves to?

**Comment by akaleeroy** [comment]
`$file` is a placeholder for the full path to a file. In Windows it resolves to something like `C:\path\to\file.md`

**Comment by joeyespo** [comment]
@akaleeroy Ok good, that's what I thought you meant.

So to be clear, you're running and seeing the following, right?

```bat
C:\grip-test>dir
 Volume in drive C has no label.
 Volume Serial Number is [...]

 Directory of C:\grip-test

01/03/2016  01:28 PM    <DIR>          .
01/03/2016  01:28 PM    <DIR>          ..
01/03/2016  01:28 PM             6,518 image.svg
01/03/2016  01:28 PM                30 README.md
               2 File(s)          6,548 bytes
               2 Dir(s)           [...] bytes free


C:\grip-test>grip.exe --browser "C:\grip-test\README.md"
```

And loading `http://localhost:6419/` shows a Grip page with a broken SVG. Does it look like this?

![broken-image](https://cloud.githubusercontent.com/assets/634573/12080123/3b4cb7da-b21f-11e5-9d77-bbce9dceff91.png)

Also, does visiting `http://localhost:6419/image.svg` show a 200 or a 404 request in the terminal?

**Comment by akaleeroy** [comment]
Yep, that's correct.

Visiting `http://localhost:6419/image.svg` shows a 200 but doesn't render the image as an image. Instead it attempts to parse it and shows

![Failed attempt at parsing SVG file as markdown instead of rendering as image](https://cloud.githubusercontent.com/assets/4068718/12080928/937f31c2-b273-11e5-9d05-d519447fa56b.png)

What it should show is the correctly rendered image:
![Correctly rendered SVG I used](https://cloud.githubusercontent.com/assets/4068718/12080940/e3a1a810-b273-11e5-9f1a-8b61eac8a299.png)

**Comment by joeyespo** [comment]
Interesting. I'm not able to reproduce.

What version of Grip are you using?

```bat
> grip -V
```

What version of Python?

**Comment by akaleeroy** [comment]
Grip 4.1.0, Python 2.7.11. 
Tried it in every browser.

**Comment by joeyespo** [comment]
Any luck on this?

I was *only* able to reproduce if I run `grip` on the image file directly and visiting `http://localhost:6419/`. (Visiting `http://localhost:6419/image.svg` rendered the image just fine.)

```bash
$ grip image.svg
 * Running on http://localhost:6419/ (Press CTRL+C to quit)
```

![preview](https://cloud.githubusercontent.com/assets/634573/13035827/90a543f0-d326-11e5-8621-044c200b4250.png)

But that's not what you're doing. So hmmm.

Could you upload the SVG file somewhere? Or try saving the following to `README.md` and running `grip` on it?

```md
Testing!
========

![Works!](https://upload.wikimedia.org/wikipedia/commons/3/30/Vector-based_example.svg)
```

**Comment by akaleeroy** [comment]
Fetching from the web works, but if I save the image it doesn't. What happens instead I described above.

`![Doesn't work!](image.svg)`
`http://localhost:6419/image.svg`

**Comment by joeyespo** [comment]
Wow, this is baffling. I just re-read this whole thread to make sure I didn't miss anything.

I wonder if the MIME type is getting confused somehow. Could you try the following?

1. Run Python
2. `import mimetypes`
3. `mimetypes.guess_type('image.svg')`

And let me know what gets returned. Thanks for being patient with this!

**Comment by akaleeroy** [comment]
```
>>> import mimetypes
>>> mimetypes.guess_type('image.svg')
(None, None)
```

I killed my Python 2 and installed Python 3. `mimetypes.guess_type` returns `('image/svg+xml', None)` and grip works as expected.

I do not know what the f^@# happened but f*^% Python on Windows.
Thanks for the help, I guess you can close this now.

**Comment by joeyespo** [comment]
FYI, v4.2.0 contains a fix for this. Grip will now render SVGs when using Python 2.6 and below.

Thanks for opening and being patient with this issue, @akaleeroy!
