### ISSUE TITLE
automatically open in a browser

### ISSUE THREAD

**Issue by whit537** [joeyespo/grip#161]
Easily done with [`webbrowser`](https://docs.python.org/2/library/webbrowser.html), see [`antigravity.py`](https://github.com/python/cpython/blob/master/Lib/antigravity.py) for example usage. ;-)

```python
import webbrowser

webbrowser.open("http://localhost:6419/")
```

**Comment by joeyespo** [comment]
Hey Chad! Haha, I did not know about that builtin import.

This feature is already in; simply run Grip with `-b` :smiley: (It also waits for the server to start before opening a page.) Any ideas how to make this stand out more in the [Usage](https://github.com/joeyespo/grip#usage)?

Thanks for the issue!

**Comment by whit537** [comment]
Ah, perfect!

> Any ideas how to make this stand out more in the Usage?

Nope, I just need to read the fun manual. :-)

Thanks! :dancer:
