### ISSUE TITLE
Links of type [[...]] not supported

### ISSUE THREAD

**Issue by aviaryan** [joeyespo/grip#163]
Links of the format `[[....]]` are not supported by grip . In this type, markdown like ``[[A Link]]`` links to `A-Link.md` in the same directory. They have been used extensively in [android-guides wiki](https://github.com/codepath/android_guides/wiki) 

```
* [[Using Context]] (What is context and how is it used?)
* [[Android Directory Structure]] (Files and Folders for Android apps)
* [[Organizing your Source Files]] (Cleaning up source of your apps)
```

Grit detects "What is context and how is it used?" as the link.

**Comment by joeyespo** [comment]
Wiki-specific features aren't supported by the [GitHub markdown API](https://developer.github.com/v3/markdown/), and so aren't supported by Grip either. The workaround is to use the more general Markdown syntax `[A-Link.md](a link)`.

Thanks for the issue, @aviaryan.
