### ISSUE TITLE
Expose render_inline parameter to the users

### ISSUE THREAD

**Issue by mrexmelle** [joeyespo/grip#164]
Exposing render_inline gives the user a flexibility whether to have the css style separated or inlined in the html. The default will still be True when exporting, and False when grip is used as a service.

**Comment by mrexmelle** [comment]
Pull request #165 has been created.

**Comment by joeyespo** [comment]
Just published v4.2.0 which contains this.

CLI was renamed option to `--no-inline`. After playing with it, `--inline=True` when using the grip server didn't make as much sense. `So --no-inline` is the new name and it only works with `--export`.

Thanks for the idea and for diving in, @mrexmelle!
