### ISSUE TITLE
Style issues in Grip 4.x

### ISSUE THREAD

**Issue by p3k** [joeyespo/grip#169]
For comparison, here is what a markdown file looks like in Grip 3.3.0…

![selection_002](https://cloud.githubusercontent.com/assets/16631/13606222/841de36c-e54b-11e5-8b4c-bba2237f5f23.png)

…and Grip 4.1.0:

![selection_001](https://cloud.githubusercontent.com/assets/16631/13606232/8d0088e0-e54b-11e5-9860-3ca3a119ebf7.png)

I already tried `grip --clear` but it did not help. Any ideas what could cause this?

_Chromium Version 48.0.2564.116 Ubuntu 15.10 (64-bit)_

**Comment by joeyespo** [comment]
Yes, this is the style issue outlined in #166. Thanks for the screenshots! That'll help anyone who comes here looking for help.

Closing as a duplicate. A fix will be up shortly.

**Comment by joeyespo** [comment]
FYI, Grip v4.2.0 was just released which contains the fix for this.

Upgrade with `pip install --upgrade grip`. The old styles will be cleared automatically with the upgrade.

Thanks, @p3k!
