### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by p3k** [joeyespo/grip#170]
I have two markdown documents, let’s call them Foo and Bar; they reside as files Foo.md and Bar.md in the GitHub wiki repository.

From Foo I am linking to Bar using this syntax:

```
[Bar](Bar)
```

While the link works as expected on GitHub, I get a 404 when using Grip – of course, I agree, Grip links to `/Bar` instead of `/Bar.md`… However, adding `.md` will break the link at GitHub.

How would I write the markdown in a way that both, GitHub and Grip, will link the two documents correctly?

**Comment by dawsonbotsford** [comment]
Have you tried `[Bar](./Bar.md)`? I'm thinking this is an issue in your understand of what is vanilla markdown and what is GitHub flavored markdown. They are different in some fairly minute ways: [About GitHub flavored markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by JasonYao** [comment]
Per https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links,

> [I'm a relative reference to a repository file](../blob/master/LICENSE)

So in OP's scenario, specifying the full path in foo will make it work with grip while still working with github:

In Foo:
> [Bar](Bar.md)

**Comment by p3k** [comment]
Thanks @JasonYao for the pointer and suggestion – could you please add the Markdown source of the link examples?

I only can assume it is something like `[Bar](./Bar.md)`…?

**Comment by joeyespo** [comment]
@p3k Yeah, go with what @dawsonbotsford is recommending with `[Bar](./Bar.md)`.

It's more of a coincidence that one absolute URL works with GitHub and another works with grip. Relative URLs make more sense when linking Markdown files on GitHub.

**Comment by akagomez** [comment]
I think the OP is pointing out a valid issue. `[Foo](./Foo.md)` doesn't work in a GitHub wiki. 

See this example: [https://github.com/akagomez/can-firebase/wiki/Foo.md](https://github.com/akagomez/can-firebase/wiki/Foo.md) 

However, this example does work: [https://github.com/akagomez/can-firebase/wiki/Foo](https://github.com/akagomez/can-firebase/wiki/Foo.md)

For wiki mirroring to work as is suggested in the [README](https://github.com/joeyespo/grip#create-a-local-mirror-of-a-github-wiki), `grip` needs to serve `/Foo.md` when `/Foo` is requested.

**Comment by joeyespo** [comment]
Interesting. From your example, @akagomez, looks like including `.md` redirects to the Markdown source file at raw.githubusercontent.com.

#175 attempts to render all Wiki-style links, including adding an extension if it's not provided, addressing this issue. Since that PR covers all the Wiki link cases, let's move the discussion there.
