### ISSUE TITLE
Display size mismatch

### ISSUE THREAD

**Issue by JasonYao** [joeyespo/grip#173]
## Issue:
- Display size is mismatched, images below for verification. It looks like the issue occurs when using
`#` or `##`, causing it to be left shifted compared to the rest of the document, which then removes the side lines and causes the overflow.

## Potential fix:
Add a css over ride for a right shift on headers, or wrap everything inside of a div to ensure it's consistent, and not overflowing to the left.

## Personal solution
So I reinstalled multiple times. It resulted in the error on 3.5.1 the first install, error on 2.7.11 on the second install, but then fixed itself on 3.5.1 on the third install. Not sure if it's a result of all the reinstalls, but end result is the bug disappears. Opening this issue in case others run into the same issue, though you can close if I'm incorrect.

## OS:
- OSX 10.11.3 El Capitan

## Browsers checked:
- Firefox (45.0.2)
- Chrome (49.0.2623.112 (64-bit))

## Python versions checked:
- 2.7.11
- 3.5.1

## Image verification - issue:
Python 2.7.11, Chrome example 1:
![python2 7 11chromeex1](https://cloud.githubusercontent.com/assets/3739191/14482433/c0aab352-010a-11e6-9795-ce55b719d48e.png)

Python 2.7.11, Firefox example 1:
![python2 7 11firefoxex1](https://cloud.githubusercontent.com/assets/3739191/14482434/c0acf158-010a-11e6-9af7-837166ed0d16.png)

Python 2.7.11, Firefox example 2:
![python2 7 11firefoxex2](https://cloud.githubusercontent.com/assets/3739191/14482435/c0ae7fa0-010a-11e6-9813-3c83678be564.png)

## Image verification - fixed
Python 3.5.1, Chrome: fixed after 3rd reinstall
![python3 5 11chrome](https://cloud.githubusercontent.com/assets/3739191/14482552/02857982-010c-11e6-8de1-f3c128bb4249.png)

Python 3.5.1, Firefox: fixed after 3rd reinstall
![python3 5 11firefox](https://cloud.githubusercontent.com/assets/3739191/14482553/028697c2-010c-11e6-8644-05d441a8c3a8.png)

**Comment by joeyespo** [comment]
Was the 3rd reinstall within the past half hour? I *just* published Grip 4.2.0, which contains a style fix. That might be what you saw.

Closing this, but feel free to re-open if that wasn't the problem afterall.

Also, thanks for all the detailed in this issue! It's *really* helpful when context and screenshots like you have here are provided :smile:

**Comment by JasonYao** [comment]
No worries, and yes, the third install was using the recently published `4.2.0`, which appears to have solved the styling issues - great job pre-empting the fix!

**Comment by joeyespo** [comment]
@JasonYao :smiley: 

Keep up those awesome bug reports.
