### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by andrewbernard** [joeyespo/grip#174]
Running grip on openSUSE Leap 42.1 I receive the following error:

```
* Running on http://localhost:6419/ (Press CTRL+C to quit)
 * Error: could not retrieve styles: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
127.0.0.1 - - [16/Apr/2016 13:15:50] "GET / HTTP/1.1" 500 -
```

My github credentials are correctly given. What is causing this?

**Comment by andrewbernard** [comment]
Solved. Many apologies. I had failed to upgrade to the latest version of grip after doing the initial pip install. Sorry for the noise.

A very nice program!

**Comment by joeyespo** [comment]
It's all good! Thanks for the update :smile: Glad you were able to resolve the problem.
