### ISSUE TITLE
Grip fails with error "failed to create process"

### ISSUE THREAD

**Issue by Samcfuchs** [joeyespo/grip#178]
On my Windows 10 machine, I installed grip with pip. When I try to start grip, it fails, saying `failed to create process.` It does so with or without passing it a file.

**Comment by joeyespo** [comment]
I ran into something like this once before. Does [this answer](http://stackoverflow.com/a/30832759/233098) help?

**Comment by joeyespo** [comment]
Going to close this for now. If that StackOverflow answer doesn't help, feel free to re-open.

Thanks, @Samcfuchs!
