### ISSUE TITLE
Broken --export command

### ISSUE THREAD

**Issue by JasonYao** [joeyespo/grip#182]
## The issue
Using the `--export` command on both virtualenvs and normal envs causes a deadlock, and no output generation of an HTML file.

## Environment
**OS**: macOS 10.11.5
**grip version**: 4.2.0 (blaze it)

## Reproduction steps
Per #180:
```sh
# Installs testing envs
pyenv install 2.6.6
pyenv install 2.7.9
pyenv install 2.7.11
pyenv install 3.5.1
pyenv virtualenv 2.6.6 grip-test-2.6.6
pyenv virtualenv 2.7.9 grip-test-2.7.9
pyenv virtualenv 2.7.11 grip-test-2.7.11
pyenv virtualenv 3.5.1 grip-test-3.5.1

## Tests (we use the grip README.md for testing)
wget https://raw.githubusercontent.com/yyuu/pyenv-virtualenv/master/README.md -O test.md

# 2.6.6
pyenv global grip-test-2.6.6
pip install grip
grip --export test.md

# 2.7.9
pyenv global grip-test-2.7.9
pip install grip
grip --export test.md

# 2.7.11
pyenv global grip-test-2.7.11
pip install grip
grip --export test.md

# 3.5.1
pyenv global grip-test-3.5.1
pip install grip
grip --export test.md

# Tests full python versions
pyenv global 2.6.6
pip install grip
grip --export test.md

pyenv global 2.7.9
pip install grip
grip --export test.md

pyenv global 2.7.11
pip install grip
grip --export test.md

pyenv global 3.5.1
pip install grip
grip --export test.md
```

## Result
All environments could generate the file using the normal `grip test.md` command, but could not bypass and directly generate an html file via the `--export` command.

**Comment by joeyespo** [comment]
Wow, thanks for digging in to this issue, @JasonYao! It was very helpful.

I found the cause last night. Will post a fix and more details tonight or tomorrow :zap:

**Comment by joeyespo** [comment]
FYI v4.3.0 has just been published with this fix. `pip install --upgrade grip` :zap:
