### ISSUE TITLE
Adding a feature for the href

### ISSUE THREAD

**Issue by nViso** [joeyespo/grip#186]
Hi,

I have a small problem with the links in the HTML files created by Grip.. Currently, I'm exporting some MD files to HTML files and I serve them in an iFrame in my website.. 

When I click on the links in the MD files, everything is always displayed in the iFrame.. This is normal when we click on the links to navigate between the MD files.. But for the other links (starting with http or https), it should not display them in the iFrame.. 

So, is there a way to check if the link starts with http or https and if it's the case add target="blank" in the href field? 

Thank you very much.

**Comment by joeyespo** [comment]
I don't think Grip is the right place to solve this. Adding `target="_blank"` isn't what you want when using Grip normally.

One possible workaround for you would be to run your exported HTML files through a transform script that adds that to all `<a>` elements that contain fully qualified `href` attributes.

[Here's what a quick search resulted in](http://stackoverflow.com/questions/33621157/python-or-etc-process-html-to-add-target-blank-to-a-tags-not-in-domain-list). Seems like a good starting point. If you make the script work with stdin/stdout, it can probably be done in a single function. Then you can write:

```bash
$ grip --export my.md | blankify.py > my.html
```

Hope this helps!
