### ISSUE TITLE
stylesheet url error in exported html

### ISSUE THREAD

**Issue by jemyzhang** [joeyespo/grip#200]
in the head of the generated html document, the href without http or https.
as of
```
<link rel="stylesheet" href="//octicons.github.com/components/octicons/octicons/octicons.css" />
```

**Comment by joeyespo** [comment]
Oops, forgot about this issue. This should be fixed as of v4.3 since the icons aren't coming from GitHub anymore.

Be sure to run `pip install --upgrade grip` and feel free to re-open if this is still a problem.
