### ISSUE TITLE
Add Homebrew to installation instructions

### ISSUE THREAD

**Issue by zmwangx** [joeyespo/grip#201]
I've been using grip for years and love it. Recently I submitted grip to [Homebrew](http://brew.sh/),  which I believe is the most popular package manager on OS X, and is really nice for installing, managing, and auto updating command line utilities. See the grip package at https://github.com/Homebrew/homebrew-core/blob/master/Formula/grip.rb and http://braumeister.org/formula/grip. I will be responsible for maintaining the package.

Would you mind adding Homebrew to [Installation](https://github.com/joeyespo/grip#installation)? It could be something like:

---

On OS X, you can also install grip with Homebrew:

    $ brew install grip

**Comment by joeyespo** [comment]
Wow, awesome! Thanks for taking initiative on this :smile: I think it'll absolutely lower the barrier for a large number of Mac users.

Done in #202.

**Comment by zmwangx** [comment]
Cool, thanks.
