### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by xxd3vin** [joeyespo/grip#206]
When I run the command below:

```
$ export GRIPURL=$(PWD)
```

I came to this error

```
$ export GRIPURL=$(PWD)
PWD: command not found
```

So I think `PWD` should be `pwd`

```
$ export GRIPURL=$(pwd)
```

**Comment by joeyespo** [comment]
Oops, looks that way. Thanks!

Want to open a PR and take the credit for the commit?

**Comment by xxd3vin** [comment]
Sure, I will correct it in PR.
