### ISSUE TITLE
Feature request: math

### ISSUE THREAD

**Issue by krey** [joeyespo/grip#208]
While GitHub does not support the insertion of latex into markdown, it would be a very useful feature for grip.
In-browser this can be using [MathJax](https://github.com/mathjax/MathJax)

**Comment by JasonYao** [comment]
Why bother if the README file is to be displayed on github anyways? This sounds like it should be a feature request for github's README renderer, not for grip.

**Comment by krey** [comment]
@JasonYao: I wasn't talking about README files, I'm thinking of .md files in general

**Comment by JasonYao** [comment]
Right, I'm saying that if the github .md renderer doesn't render latex code, why would `grip` want to render it?

The main purpose of grip is to preview .md files and see how they'd look **on github**, if `grip` adds this and starts diverging from what github displays, then it defeats the purpose of `grip` in the first place.

**Comment by krey** [comment]
@JasonYao: yeah, I guess it depends on what people wanna use this for. I've found that `grip` is one of the best markdown renderers out there and would like to use it as such.

If you're worried about divergence from github, make the LaTeX feature opt-in

**Comment by joeyespo** [comment]
@krey Thanks for the kind words 😄 

If you want to use Grip more generally, may I suggest using [the Python API](https://github.com/joeyespo/grip#api) to inject the custom pieces you need? Something like:

```python
# gripjax.py

from grip import GitHubRenderer, Grip

MATHJAX_SCRIPT = """
<script async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML"></script>
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" onload="javascript:MathJax.Hub.Queue(['Typeset', MathJax.Hub]);">
"""

class MathJaxRenderer(GitHubRenderer):
    def patch(self, html):
        return super(MathJaxRenderer, self).patch(html) + MATHJAX_SCRIPT

Grip(renderer=MathJaxRenderer()).run()
```

Then run `gripjax.py` instead of `grip`.

Note that this is a bit of a hack. Namely, using `patch` instead of some dedicated `scripts` option. And the `<img>` trick so that the `MathJax.Hub.Queue` code will run on each auto-reload. (See [this](http://stackoverflow.com/questions/1197575/can-scripts-be-inserted-with-innerhtml) and [this](http://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml) and [this](https://docs.mathjax.org/en/v2.5-latest/typeset.html).)

I'm considering adding a way to more easily inject styles and scripts using the API or even globally with [configuration](https://github.com/joeyespo/grip#configuration). Until then, this should work for you. However, I don't plan to hardcode MathJax or any other custom library into this repo.

Hope this helps!

**Comment by ludaavics** [comment]
@joeyespo Thanks for this!
FWIW, I am in the same boat as @krey and use `grip` as my go to renderer.

To confirm, your hack above only works if we install `grip`by cloning the repo, yes (as opposed to Homebrew)?
I would definitely use a "clean" way of adding MathJax support!

**Comment by drorata** [comment]
I'll just put it here: https://github.com/github/markup/issues/897

**Comment by ludaavics** [comment]
@joeyespo it looks like f17a68a551eac610d4ee3335aabe6141e0620567 broke this quick fix.
Have you given more thoughts on allowing to inject custom scripts? I see there is now an option for styles, but doesn't look like there is one for scripts -- let me know if missing something.

This is out of my wheelhouse, but happy to work on it to the extent that I can help

**Comment by ztlevi** [comment]
It looks like github now support math equations. How can we achieve with grip?

**Comment by nh2** [comment]
> It looks like github now support math equations

@ztlevi Is that true? Source or link to how it works?

**Comment by nh2** [comment]
> @joeyespo it looks like [f17a68a](https://github.com/joeyespo/grip/commit/f17a68a551eac610d4ee3335aabe6141e0620567) broke this quick fix.

@joeyespo Does the current API still allow injecting custom scripts?

It would be extremely useful for my project to support that.

**Comment by ztlevi** [comment]
@nh2 I forget where I see it. But I just did a little google, and it turns out Gitlab supports it natively https://gitlab.com/gitlab-org/gitlab/blob/master/doc/user/markdown.md#math

**Comment by nh2** [comment]
@ztlevi Ah, that's Gitlab though, not Github.

Still interesting to know Gitlab supports it.

**Comment by dgilford** [comment]
It would be great to resurrect this, grip support for math to match GitHub previews would be very useful.

**Comment by Hermann-web** [comment]
@dgilford, you're right. It would be useful

**Comment by xrchz** [comment]
Why does `grip` not support LaTeX? This is a feature in GitHub markdown. I thought `grip` was supposed to emulate GitHub?

**Comment by unhappychoice** [comment]
mdts has math support and might work for your LaTeX needs. You can try it with `npx mdts` to see if it handles your specific math expressions well.

https://github.com/unhappychoice/mdts

Worth testing as an alternative while waiting for full LaTeX support in grip.
