### ISSUE TITLE
Cannot install with brew

### ISSUE THREAD

**Issue by claucece** [joeyespo/grip#212]
Hi!

When trying to install with Brew, this error showed up: 

> brew install grip
> Error: No available formula with the name "grip" 
> ==> Searching for similarly named formulae...
> Error: No similarly named formulae found.

Is there not a grip formulae on Brew now?

**Comment by joeyespo** [comment]
Hey @zmwangx, any thoughts on this?

**Comment by zmwangx** [comment]
```
brew update
```

If that doesn't help:

```
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```

**Comment by joeyespo** [comment]
Thanks, @zmwangx! 😃 

@claucece, did that work for you? If not, feel free to re-open with some more context.

**Comment by claucece** [comment]
@joeyespo Yes! Thanks!
