### ISSUE TITLE
`grip --browser 0` properly supports random port, but doesn't launch browser

### ISSUE THREAD

**Issue by hollasch** [joeyespo/grip#218]
If you run `grip --browser`, it will launch a new page for that grip session. However, if you use the random port feature (`grip --browser 0`), then `--browser` doesn't work.

**Comment by jwilk** [comment]
This seems non-trivial to fix.
AFAICT, flask/werzeug don't expose the socket to us, where we could check what's that actual port that was bound.
Perhaps `werkzeug.serving.make_server()` could be monkey-patched?

**Comment by joeyespo** [comment]
Good find, @hollasch!

I think I found a workable solution without getting too invasive. @jwilk Yeah, that was my first though too. Check out #219. I think that solution may be more stable by not depending on Flask/Werkzeug internals.

Thanks!

**Comment by joeyespo** [comment]
Fixed by #219.
