### ISSUE TITLE
Suggestion for how to enter field values in ~/.grip/settings.py

### ISSUE THREAD

**Issue by erikrtn** [joeyespo/grip#232]
Regarding https://github.com/joeyespo/grip#configuration may be helpful to explicitly instruct user to add field values inside single quotes.

Can be done by either linking to https://github.com/joeyespo/grip/blob/master/grip/settings.py for example syntax, or providing an example, e.g.

```
USERNAME = 'thisismyusername'
PASSWORD = '1234512345'
```

This is sort of obvious if you use Python but may not be obvious to everyone.

**Comment by ralanbowman** [comment]
I spent an hour trying to figure out why I was getting `not defined` errors related to my USERNAME and PASSWORD. I'm a tech writer, not a Python dev, so using single quotes would have never occurred to me. Please add this to the existing docs to save someone else the trouble.

**Comment by joeyespo** [comment]
This is [now in](https://github.com/joeyespo/grip#configuration). Thanks for the suggestion. 😃
