### ISSUE TITLE
When using --quiet with --export, message is displayed

### ISSUE THREAD

**Issue by andygock** [joeyespo/grip#238]
When using `--quiet` with `--export`, "Exporting to foobar.html" is printed to console.

**Comment by kagof** [comment]
I've created a pull request ( #247 ) which addresses this issue. The test suite is failing, however I'm not convinced that the test suite is valid anymore, especially as every open pull request fails it.

**Comment by joeyespo** [comment]
@kagof Yeah, looks like Python 2.6 is having trouble. All the other versions are passing though.

If anyone stumbles across this, looks like the error is ['No module named _io'](https://travis-ci.org/joeyespo/grip/jobs/288425993), which a quick search says may be a corrupt virtualenv. Not sure why it's only happening on 2.6, but should be ok to pull in. (Will review soon!)
