### ISSUE TITLE
'Grip' name already taken by other tool

### ISSUE THREAD

**Issue by WebDragon** [joeyespo/grip#257]
```
$ sudo dnf info grip
Last metadata expiration check: 0:27:52 ago on Tue Jan  9 09:42:33 2018.
Available Packages
Name        : grip
Arch        : x86_64
Epoch       : 1
Version     : 3.6.1
Release     : 2.fc25
Size        : 520 k
Repo        : updates
Summary     : Front-end for CD rippers and Ogg Vorbis encoders
URL         : https://sourceforge.net/projects/grip/
License     : GPLv2+
Description : Grip is a GTK+ based front-end for CD rippers (such as cdparanoia and
            : cdda2wav) and Ogg Vorbis encoders. Grip allows you to rip entire tracks or
            : just a section of a track. Grip supports the CDDB protocol for
            : accessing track information on disc database servers.
```

**Comment by joeyespo** [comment]
This is bound to happen when using a short names for CLI tools.

Thanks for opening the issue, but I don't think there's really anything actionable here. Renaming it would be a major headache for everyone--especially those who formed the muscle memory of typing `grip`.

If you want to use both, perhaps create an alias that points to the Python script, e.g. `grip-py` or `gripy`, or even rename the Python script directly after install. I'm not that familiar with `dnf`, so if you have any better ideas or workarounds, feel free to post them here.

Hope that helps!

**Comment by WebDragon** [comment]
Asking the more established package to readdress their own muscle-memory seems a bit egocentric, don't you think? 
Plus, It's not the only one. https://www.projectmanagement.com/tools/249065/GRIP-IT

on the other hand there doesn't seem to be anything named 'grippy' (and since yours is already grip.py the name seems obvious and easier to transition to. glad you thought of it.)

**Comment by joeyespo** [comment]
> Asking the more established package to readdress their own muscle-memory seems a bit egocentric, don't you think?

No, no, I wasn't suggesting that at all. My only point is name clashes are bound to happen.

I wouldn't suggest either one change its name. Rather, we live with it and try to work together (e.g. using aliases, exposing multiple binaries, or, e.g. this repo registering as "grip-py" in that package manager--but not necessarily changing its CLI name).
