### ISSUE TITLE
--quiet does not seem to work.

### ISSUE THREAD

**Issue by bperrybap** [joeyespo/grip#259]
If exporting to a file using a command line like this:
```
grip --quiet --title=README README.md --export $HTMLdocs/README.html
```

grip still outputs an  "exporting" message like this:
```
Exporting to ./examples/Documentation/Docs/README.html
```

**Comment by joeyespo** [comment]
I just released 4.5.1, which contains a fix. Be sure to upgrade with `pip install --upgrade grip`.

Thanks for the issue, @bperrybap!
