### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by craftyguy** [joeyespo/grip#261]
@joeyespo 

Is this project still being maintained?

**Comment by joeyespo** [comment]
Yes, it is!

I tend to come back to this project and implement in batches. I admit I'm overdue for one, but do intend to visit issues soon.

Thanks for checking and for using Grip 😃

**Comment by craftyguy** [comment]
Great! I just took over the packaging of this in Arch Linux's AUR.

**Comment by joeyespo** [comment]
Excellent! Thank you for doing so!

**Comment by dreua** [comment]
What's the current status here? For example, #309 is an easy fix and didn't see any action for some time.
