### ISSUE TITLE
CSS issue - Style not matching GitHub

### ISSUE THREAD

**Issue by OisinMoran** [joeyespo/grip#291]
First off, I love grip, so thank you!

I just installed it for the first time on this machine via `apt install grip` and there was no styling whatsoever when I ran `grip -b filename.md`. I then checked this repo and saw it says to run `pip install grip` to install it, so uninstalled and ran that. Now I'm getting styling that is closer to GitHub's but still not quite there (which is an even weirder problem really). I have attached a screenshot in which you'll notice the full border is not there and the padding is too small (probably the same cause).

![image](https://user-images.githubusercontent.com/8939851/55416532-daf49d00-5566-11e9-9fae-36755ae95ee6.png)

I have tried `grip --clear` (does not change anything) and `grip -V` gives the version as `Grip 4.5.2`.

Any help would be greatly appreciated :slightly_smiling_face:

**Comment by Emi1305** [comment]
The issue seems to be that the URL `https://octicons.github.com/components/octicons/octicons/octicons.css` returns a 404 Not Found, I wasn't able to find the actual path to the file

**Comment by OisinMoran** [comment]
Weird! Where is that referenced? Searching in the code I can only find links to https://github.com/joeyespo/grip/blob/master/grip/static/octicons/octicons.css, which does exist.

**Comment by Emi1305** [comment]
I saw the request in the browser's develper tools. 

I can't check it right now as I'm not on the same computer, but I think I've the version that is available on the Ubuntu repositories, maybe it is outdated

**Comment by OisinMoran** [comment]
I am on Ubuntu, but just checked there and I have version 4.5.2 so unfortunately not fixed by updating.

**Comment by RuRo** [comment]
Same issue here. I also have version 4.5.2 and missing borders like in the image.

**Comment by jessevdp** [comment]
I'm also having this issue. I just installed grip (like minutes ago) through homebrew. My current version is `4.5.2`.

Note the top browser window is showing grips output. The bottom window is showing GitHub directly.

<img width="1160" alt="Screenshot 2020-03-14 at 17 36 40" src="https://user-images.githubusercontent.com/15139826/76686392-4837fb80-661b-11ea-925f-662cc1d44958.png">
