### ISSUE TITLE
Container styling is broken

### ISSUE THREAD

**Issue by raxod502** [joeyespo/grip#315]
This is what my README looks like on GitHub:

![image](https://user-images.githubusercontent.com/6559064/78512377-356b9f00-7761-11ea-9956-a8ce40de96ae.png)

This is what it looks like under Grip:

![image](https://user-images.githubusercontent.com/6559064/78512379-3dc3da00-7761-11ea-90d1-3dc6084f7b75.png)

Is this a known issue?

**Comment by luismarques** [comment]
I also experienced the same issue.

**Comment by arlofaria** [comment]
I believe this might be related to #297 and #304

**Comment by raxod502** [comment]
Oh, beautiful -- I had no idea the bug was already fixed. I simply switched from [python-grip](https://aur.archlinux.org/packages/python-grip/) to [python-grip-git](https://aur.archlinux.org/packages/python-grip-git/) and the problem was solved in 30 seconds. I guess I'll close this given that the only thing that needs to be done is #304.
