### ISSUE TITLE
The meaning of the name

### ISSUE THREAD

**Issue by alexandre-mbm** [joeyespo/grip#320]
"grip", here at project, what it means?

A tool to do "grips" (adjustments) in the preview?

Is it a recursive acronym, abbreviation or something?

**Comment by thierryc** [comment]
grip = Github Readme Instant Preview.

**Comment by joeyespo** [comment]
@thierryc - yep, that's it 😃 Thanks for answering, and thanks for the question @alexandre-mbm for anyone else searching the repo for an answer.
