### ISSUE TITLE
code blocks not redenring correctly in grip

### ISSUE THREAD

**Issue by luispresuelgit** [joeyespo/grip#349]
Actual output:

![image](https://user-images.githubusercontent.com/14104201/147283108-133a7401-ef3f-4c6e-b2fa-1e1f5e635bb3.png)

Expected output:

![image](https://user-images.githubusercontent.com/14104201/147283149-e7025b7a-46d0-4c2e-bb84-ca9732a18cb4.png)

Enviroment:
$ python --version
Python 3.8.10

**requirements.txt:**
```
certifi==2021.10.8
charset-normalizer==2.0.9
click==8.0.3
docopt==0.6.2
Flask==2.0.2
grip==4.5.2
idna==3.3
importlib-metadata==4.10.0
itsdangerous==2.0.1
Jinja2==3.0.3
Markdown==3.3.6
MarkupSafe==2.0.1
path-and-address==2.0.1
Pygments==2.10.0
requests==2.26.0
urllib3==1.26.7
Werkzeug==2.0.2
zipp==3.6.0
```

**Comment by jpmvferreira** [comment]
I'm getting the same problem on a clean python venv.

Also, the entire file seems to be in black and white, without any coloring, in and outside the code blocks.
Here's the output in Github:
![image](https://user-images.githubusercontent.com/41581666/147576109-c386738f-99ad-47cb-b7b2-22b22913938f.png)

And here's the output when using `grip`:
![image](https://user-images.githubusercontent.com/41581666/147576186-cb1f1930-40eb-4ebd-9063-369952bff124.png)

However links work correctly, despise not being highlighted.

**Comment by sparktx-mark-welsh** [comment]
I'm seeing the same issue, Python 3.8.3

**Comment by Jach** [comment]
This was fixed for me when I upgraded from my distro's grip-4.5.2-r2 to its current 4.6.0 version.

**Comment by luispresuelgit** [comment]
There was another error in the 4.6.0 version that wouldn't let me start grip itself. I just upgraded the latest version (at moment of this comment, [4.6.1](https://github.com/joeyespo/grip/releases/tag/v4.6.1)) that was released today and seemed to be working
