### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by rr-** [joeyespo/grip#351]
Since this project seems to be unmaintained and author seems to be no longer responding to the issues, this issue serves as a place to discuss its future.

Is there currently any fork that has up to date styles from GitHub? Is any of the growing list of forks popular enough to serve as a future point of reference?

**Comment by joeyespo** [comment]
Hi @rr- 

Version 4.6.0 with the remaining style fixes has just been released. More updates on the way. Thanks for opening the issue.

**Comment by rr-** [comment]
!!! :heart: 

Thank you
