### ISSUE TITLE
Troubleshoot newbie

### ISSUE THREAD

**Issue by jimcrayne** [joeyespo/grip#70]
I used pip install grip, and it reports that I have the package installed.

However, the command "grip" is not in my path and nowhere to be found.

(NB: I do not usually use pip, this is my first time, so my issue might be something
 that would not affect more expirienced users.)

**Comment by joeyespo** [comment]
Any luck recently?

**Comment by joeyespo** [comment]
Just released 3.1.0. This was a weird one. I'd recommend reinstalling Python because something just isn't right. Going to close it for now since it's more of a configuration problem (or pip's entry point feature for installing CLI packages) than a grip problem. Feel free to open a new issue if you reinstall and are still having trouble though and I'll do what I can to walk through it with you again.

**Comment by ngokli** [comment]
@joeyespo: I just ran into this problem on ubuntu 16.04, after installing with `pip install grip`.  `sudo pip install grip` lets me run `grip` directly from the command line.  Took me a while to find this issue on Github, though... maybe add a note in the readme?

In case someone feels clueless, this removes my user install and installs it globally:
```
$ pip uninstall grip
$ sudo pip install grip
```

When installing grip the second time, pip seems to have gotten all the dependencies from my user directory... Strange?
```
$ sudo pip install grip
The directory '/home/ng/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ng/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting grip
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.6 in /home/ng/.local/lib/python2.7/site-packages (from grip)
...
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/ng/.local/lib/python2.7/site-packages (from Jinja2>=2.4->Flask>=0.10.1->grip)
Installing collected packages: grip
Successfully installed grip-4.3.2
```

**Comment by ngokli** [comment]
Oh, and to address your earlier question to jimcrayne:
```
$ which python
/usr/bin/python
$ which pip
/usr/bin/pip
$ sudo which python
/usr/bin/python
$ sudo which pip
/usr/bin/pip
```

**Comment by davisjam** [comment]
@ngokli's solution worked for me.

**Comment by zhengzhu88** [comment]
I ran into this issue on the Linux subsystem on Windows. I ended up having to `sudo apt uninstall pip`, reinstall it through the official website, follow the instructions for installing grip, then add `alias grip=~/.local/bin/grip` in my .bashrc.

It looks like the pip in Ubuntu's default repo isn't the same as the one from pypi.

References:
https://askubuntu.com/questions/883404/pip-install-is-not-installing-executables-in-usr-local-bin
https://pip.pypa.io/en/stable/installing/

**Comment by stas00** [comment]
I had this problem with `apt` installed `grip`. The package appears to be broken.
```
$ grip
Traceback (most recent call last):
  File "/usr/local/bin/grip", line 7, in <module>
    from grip import main
ModuleNotFoundError: No module named 'grip'
```
I fixed it by removing the `apt` package, and installing it directly from `pypi` with:
```
apt remove grip
pip3 install grip -U
```

**Comment by shawn-eary** [comment]
Regarding the comment from @ngokli 

> @joeyespo: I just ran into this problem on ubuntu 16.04, after installing with `pip install grip`. `sudo pip install grip` lets me run `grip` directly from the command line. Took me a while to find this issue on Github, though... maybe add a note in the readme?
> 
> In case someone feels clueless, this removes my user install and installs it globally:
> 
> ```
> $ pip uninstall grip
> $ sudo pip install grip
> ```
> 
> When installing grip the second time, pip seems to have gotten all the dependencies from my user directory... Strange?
> 

I'm on Debian 11 (Bullseye) and had to do basically the same thing

```
shawn_eary@myBox:~$ pip uninstall grip
          ... [Bunch of uninstall messages go here] ...
shawn_eary@myBox:~$ su - root
root@myBox:~# pip uninstall grip
          WARNING: Skipping grip as it is not installed. 
root@myBox:~# pip install grip
          ... [Bunch of install messages go here] ...
root@uaf132758:~# exit
          logout
shawn_eary@myBox:~# grip
          Error: No README found at .
```

The last error message shows that Grip is working.
