### ISSUE TITLE
Password improments

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/grip#78]
Several important points and some good potential solutions were discussed in #76. This issue will track the progress and ultimately decide how passwords will be dealt with going forward.

### Overview

The problem is using GitHub's password. We shouldn't encourage people to store their passwords, both from the `PASSWORD` config variable and implicitly with bash's command history, [as @davejamesmiller points out](https://github.com/joeyespo/grip/issues/76#issuecomment-51569311).

However, `-pass` as-is can still be useful. For one, Windows doesn't save command history. In this case, it's a decent quick fix to bypass the rate limit. Also, the `PASSWORD` config variable can elegantly [grab passwords from a password manager](https://github.com/joeyespo/grip/issues/76#issue-39417791). Obviously, using a token is still preferred when hard-coding anything, but the point here is that there's still some good use cases for accepting a password.

### Proposals

1. Read passwords from STDIN when `--user` is provided without `--pass` ([suggested by @davejamesmiller](https://github.com/joeyespo/grip/issues/76#issuecomment-51569311)). This is easy for all parties, but quickly becomes repetitive for the end user.

2. [Create an authorization](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization) after prompting for your username / password and store that token in `~/.grip/.auth` ([suggested by @davejamesmiller](https://github.com/joeyespo/grip/issues/76#issuecomment-51569311)) Related issue: #82.

3. Prompt for a username / password / [token](https://developer.github.com/v3/auth/#working-with-two-factor-authentication) in the browser only *after* reaching your rate limit. This is easy and also allows the user to ignore the problem until they need to take action.

4. Wire-up your password from a password manager as [@klmr has manually done](https://github.com/joeyespo/grip/issues/76#issue-39417791).

5. Use the ENV for passing in passwords (mostly for automation)

Whatever we decide, we'll have to discourage people from entering passwords in the commandline. Although if we come up with an intuitive / noninvasive / easy solution, that might do the talking for us.

Thoughts?

**Comment by ssundarraj** [comment]
I would say make option 2 the default. If the password isn't contained in the file, fall back to option 4 and fall back to option 1 if the password isn't in the keychain. 

For automation, add a flag to get the password from ENV.

What do you think?

**Comment by joeyespo** [comment]
@ssundarraj Agreed. #82 contains that approach. Going to close this issue and move forward there. Thanks for your input!
