### ISSUE TITLE
Update docopt dependency to 0.6.2

### ISSUE THREAD

**Issue by eugene-eeo** [joeyespo/grip#79]
The latest release of docopt is `0.6.2`, you might want to look into that. I don't think it breaks anything since it has such a small API. I updated to the latest version of docopt and it broke the `grip` command.

**Comment by joeyespo** [comment]
FYI I just unpinned the dependencies in 1ad0b42d70f0340e34b0f30236ef8a8ed106c6f2, so version conflicts shouldn't be an issue going forward. Thanks!

**Comment by joeyespo** [comment]
Also, I just released 3.1.0 with that fix. Be sure to `pip install --upgrade grip`. Thanks!
