### ISSUE TITLE
Support chinese or others non-ascii language

### ISSUE THREAD

**Issue by laomo** [joeyespo/grip#86]
add 
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
before https://github.com/joeyespo/grip/blob/master/grip/server.py#L11

to support chinese file name

**Comment by joeyespo** [comment]
Ok. Makes sense.

@ssokolow Would adding the following to `command.py` work? That'll make sure that using grip as a library won't unintentionally monkey-patch the parent project.

def main(argv=None, force_utf8=True):
    """The entry point of the application."""
    if force_utf8 and sys.version_info.major == 2:
      reload(sys)
      sys.setdefaultencoding('utf-8')
    ...

**Comment by ssokolow** [comment]
That looks like it should work.

**Comment by joeyespo** [comment]
Excellent. I added that to the 3.1.0 release. Be sure to `pip install --upgrade grip`, @laomo. And thanks for your thorough help with encodings, @ssokolow!
