### ISSUE TITLE
Support multiple input files at once

### ISSUE THREAD

**Issue by clawoflight** [joeyespo/grip#88]
Maybe I'm just terrible at writing makefiles, but it would make my life a lot easier if grip would accept multiple files. You could make it so that it simply exports all of them to the same name .html, like it's done by default right now.

**Comment by zenaan** [comment]
In Github markdown, splitting your file into sections and including them like this:

\<file name="s.toplist.md"\>

does in fact render properly, if that's useful - I've used this for a long time.

Unfortunately such "include files" do not yet render in `grip` - is this a suitable bug or does this "include" feature need a separate bug?
