### ISSUE TITLE
Markdown cannot contain not latin-1 characters

### ISSUE THREAD

**Issue by syohex** [joeyespo/grip#99]
Markdown cannot be rendered if markdown file has not latin-1 chacters(Japanese characters, emoji etc).

For example, README.md is here

```
⌘
```

```
% grip --version
Grip 3.1.0
% grip README.md
```

And I accessed http://localhost:5000 then I got following error(and stack trace)

```
builtins.UnicodeEncodeError

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2318' in position 0: ordinal not in range(256)
```

How can I avoid this ? (Or is this bug ?)

Thanks for awesome tool.

**Comment by joeyespo** [comment]
Ah, yeah, this is indeed a bug.

I was able to take a look tonight. Seems grip wasn't actually encoding the Unicode text it read from the README before sending it off to GitHub, leaving requests to use the default encoding of `ISO 8859-1` (latin-1). Just deployed a fix that encodes to `UTF-8` and sets the appropriate `charset`.

Run a `pip install --upgrade grip` and let me know if this works for you.

Thanks for opening the issue, @syohex!

**Comment by syohex** [comment]
Thanks for quick fix.
I confirmed that this issue is fixed. :smile:
